-- Create a table for public profiles (to store roles)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  role text default 'user', -- 'admin', 'user'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table profiles enable row level security;
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);

-- Create a table for consultations
create table consultations (
  id bigint generated by default as identity primary key,
  client_name text not null,
  client_email text not null,
  client_phone text,
  requested_date timestamp with time zone not null,
  status text default 'pending_approval', -- 'pending_approval', 'scheduled', 'completed', 'rejected'
  payment_status text default 'unpaid', -- 'unpaid', 'paid'
  notes text,
  google_meet_link text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table consultations enable row level security;

-- Policies for consultations
-- Admins can see all, Users can insert
create policy "Admins can view all consultations" on consultations for select 
using ( exists (select 1 from profiles where id = auth.uid() and role = 'admin') );

create policy "Admins can update consultations" on consultations for update
using ( exists (select 1 from profiles where id = auth.uid() and role = 'admin') );

create policy "Public can request consultation" on consultations for insert with check (true);
