-- Create a table for product variants (specific capacities with source URLs)
create table product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id) on delete cascade not null,
  capacity text not null, -- e.g. '128GB'
  source_url text, -- Back Market URL
  price_usd numeric, -- Scraped base price
  price_kes numeric, -- Calculated final price
  last_updated timestamp with time zone,
  status text default 'active', -- 'active', 'out_of_stock', 'error'
  unique(product_id, capacity)
);

-- Enable RLS
alter table product_variants enable row level security;
create policy "Allow public read access" on product_variants for select using (true);

-- Create a log table for scraper activity to enforce limits
create table scraper_logs (
  id bigint generated by default as identity primary key,
  variant_id bigint references product_variants(id),
  status text not null, -- 'success', 'fail', 'skipped'
  message text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table scraper_logs enable row level security;
create policy "Allow public read access" on scraper_logs for select using (true);
