-- Create a table for products (phones)
create table products (
  id bigint generated by default as identity primary key,
  brand text not null, -- 'iphone' | 'samsung' | 'pixel'
  name text not null,
  series text not null,
  capacities text[] not null, -- Array of strings e.g. ['64GB', '128GB']
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create a table for global app settings (fees, currency, etc.)
create table app_settings (
  id bigint generated by default as identity primary key,
  key text unique not null,
  value jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table products enable row level security;
alter table app_settings enable row level security;

-- Create policies to allow public read access
create policy "Allow public read access" on products for select using (true);
create policy "Allow public read access" on app_settings for select using (true);

-- Insert initial settings placeholders (will be updated by seed script)
insert into app_settings (key, value)
values 
  ('KES_PER_USD', '135'::jsonb),
  ('WHATSAPP_NUMBER', '"254791873538"'::jsonb), -- JSON string
  ('AUTOMATION_SETTINGS', '{"CYCLE_DAYS": 21, "MAX_PER_DAY": 15, "DELAY_MINUTES": 2, "OPERATING_HOURS": {"START": 9, "END": 18}, "SKIP_WEEKENDS": true}'::jsonb),
  ('FEE_STRUCTURE', '{"FIXED_USD": 8, "SHIPPING_FLAT_USD": 20, "SHIPPING_PERCENT": 0.035, "SERVICE_FEE_FIXED_USD": 30, "SERVICE_FEE_PERCENT_LARGE": 0.045, "THRESHOLD_USD": 750}'::jsonb)
on conflict (key) do nothing;
