-- LEGITGRINDER MASTER SCHEMA
-- This script initializes the entire database with correct dependency ordering.
-- Run this in the Supabase SQL Editor.

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. PROFILES (Required for Admin Policies)
CREATE TABLE IF NOT EXISTS profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  email text,
  role text DEFAULT 'user', -- 'admin', 'user'
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone." ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON profiles FOR UPDATE USING (auth.uid() = id);

-- Function to handle new user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role)
  VALUES (new.id, new.email, 'user');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to call the function on signup
CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Function to create client record on signup
CREATE OR REPLACE FUNCTION public.handle_new_client()
RETURNS trigger AS $$
BEGIN
  -- Create client record from profile data
  INSERT INTO public.clients (id, name, email, phone, location, interests)
  VALUES (
    'client-' || new.id::text,
    COALESCE(new.raw_user_meta_data->>'name', 'New User'),
    new.email,
    new.raw_user_meta_data->>'phone',
    new.raw_user_meta_data->>'location',
    CASE 
      WHEN new.raw_user_meta_data->>'interests' IS NOT NULL 
      THEN string_to_array(new.raw_user_meta_data->>'interests', ',')
      ELSE '{}'
    END
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to create client on signup
CREATE OR REPLACE TRIGGER on_auth_user_create_client
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_client();

-- 2. PRODUCTS
CREATE TABLE IF NOT EXISTS products (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    price_kes NUMERIC DEFAULT 0,
    category TEXT DEFAULT 'General Products',
    stock_status TEXT DEFAULT 'In Stock',
    description TEXT,
    image TEXT,
    images TEXT[] DEFAULT '{}',
    shop_variants JSONB DEFAULT '[]',
    origin TEXT DEFAULT 'USA',
    inventory_quantity INTEGER DEFAULT 0,
    discount_price NUMERIC,
    variations TEXT[] DEFAULT '{}',
    colors TEXT[] DEFAULT '{}',
    brand TEXT,
    series TEXT,
    capacities TEXT[],
    shipping_duration TEXT,
    video_url TEXT
);

ALTER TABLE products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "products_select_all" ON products FOR SELECT USING (true);
CREATE POLICY "products_insert_admin" ON products FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
);
CREATE POLICY "products_update_admin" ON products FOR UPDATE USING (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
);
CREATE POLICY "products_delete_admin" ON products FOR DELETE USING (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
);

-- 3. PRODUCT VARIANTS (Linking back to products)
CREATE TABLE IF NOT EXISTS product_variants (
  id bigint generated by default as identity primary key,
  product_id UUID REFERENCES products(id) ON DELETE CASCADE,
  capacity text NOT NULL,
  source_url text,
  price_usd numeric,
  price_kes numeric,
  last_updated timestamp with time zone,
  is_manual_override boolean DEFAULT false,
  status text DEFAULT 'active',
  UNIQUE(product_id, capacity)
);

ALTER TABLE product_variants ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON product_variants FOR SELECT USING (true);

-- 4. CLIENTS
CREATE TABLE IF NOT EXISTS clients (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  location TEXT,
  joined_date DATE DEFAULT CURRENT_DATE,
  total_spent_kes NUMERIC DEFAULT 0,
  order_count INTEGER DEFAULT 0,
  last_order_date TEXT DEFAULT 'Never',
  interests TEXT[] DEFAULT '{}',
  purchased_items TEXT[] DEFAULT '{}',
  purchase_frequency TEXT DEFAULT 'Low'
);

ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read clients" ON clients FOR SELECT USING (true);
CREATE POLICY "Public insert clients" ON clients FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update clients" ON clients FOR UPDATE USING (true);

-- 5. CONSULTATIONS
CREATE TABLE IF NOT EXISTS consultations (
  id bigint generated by default as identity primary key,
  client_name text NOT NULL,
  client_email text NOT NULL,
  client_phone text,
  client_whatsapp text,
  requested_date timestamp with time zone NOT NULL,
  topic text,
  status text DEFAULT 'pending_approval', 
  payment_status text DEFAULT 'unpaid',
  notes text,
  fee_usd numeric DEFAULT 15,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE consultations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public insert consultations" ON consultations FOR INSERT WITH CHECK (true);
CREATE POLICY "Admin select consultations" ON consultations FOR SELECT USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
);

-- 6. SOURCING REQUESTS (PHASE 4)
CREATE TABLE IF NOT EXISTS sourcing_requests (
  id bigint generated by default as identity primary key,
  client_name text NOT NULL,
  client_whatsapp text NOT NULL,
  product_name text NOT NULL,
  product_category text,
  product_link text,
  estimated_quantity integer DEFAULT 1,
  shipping_preference text, -- 'Air' or 'Sea'
  item_type text, -- 'Fragile', 'Heavy', 'General'
  target_budget_kes numeric,
  urgency text, -- 'High', 'Medium', 'Low'
  status text DEFAULT 'pending', -- 'pending', 'viewed', 'contacted', 'completed'
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE sourcing_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public insert sourcing" ON sourcing_requests FOR INSERT WITH CHECK (true);
CREATE POLICY "Admin full access sourcing" ON sourcing_requests FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
);

ALTER TABLE consultations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins can manage consultations" ON consultations FOR ALL 
USING ( EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin') );
CREATE POLICY "Public can request consultation" ON consultations FOR INSERT WITH CHECK (true);

-- 6. BLOGS
CREATE TABLE IF NOT EXISTS blogs (
  id bigint generated by default as identity primary key,
  title text NOT NULL,
  excerpt text,
  content text,
  image_url text,
  category text,
  date date DEFAULT CURRENT_DATE,
  author text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE blogs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Blogs are viewable by everyone" ON blogs FOR SELECT USING (true);
CREATE POLICY "Admins can manage blogs" ON blogs FOR ALL 
USING ( EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin') );

-- 7. FAQS
CREATE TABLE IF NOT EXISTS faqs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    category TEXT DEFAULT 'General',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE faqs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "faqs_select_all" ON faqs FOR SELECT USING (true);
CREATE POLICY "faqs_modify_admin" ON faqs FOR ALL 
USING ( EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin') );

-- 8. APP SETTINGS
CREATE TABLE IF NOT EXISTS app_settings (
  id bigint generated by default as identity primary key,
  key text UNIQUE NOT NULL,
  value jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON app_settings FOR SELECT USING (true);

-- SEED DATA
INSERT INTO app_settings (key, value)
VALUES 
  ('KES_PER_USD', '135'::jsonb),
  ('WHATSAPP_NUMBER', '"254791873538"'::jsonb),
  ('FEE_STRUCTURE', '{"FIXED_USD": 8, "SHIPPING_FLAT_USD": 20, "SHIPPING_PERCENT": 0.035, "SERVICE_FEE_FIXED_USD": 30, "SERVICE_FEE_PERCENT_LARGE": 0.045, "THRESHOLD_USD": 750}'::jsonb)
ON CONFLICT (key) DO NOTHING;

-- 9. INVOICES (For Order History & Tracking)
CREATE TABLE IF NOT EXISTS invoices (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  invoice_number TEXT NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  client_name TEXT,
  product_name TEXT,
  status TEXT DEFAULT 'Received by Agent',
  progress INTEGER DEFAULT 0,
  last_update TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  is_paid BOOLEAN DEFAULT false,
  total_kes NUMERIC DEFAULT 0,
  paystack_reference TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;

-- Policy: Admin can do everything
CREATE POLICY "Admins have full access to invoices" ON invoices FOR ALL 
USING ( EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin') );

-- Policy: Users can view their own orders
CREATE POLICY "Users can view their own orders" ON invoices FOR SELECT 
USING ( auth.uid() = user_id );

-- Policy: Allow order creation
CREATE POLICY "Allow order creation" ON invoices FOR INSERT WITH CHECK (true);

/*
  ADMIN PROMOTION SNIPPET
  Run this AFTER you have signed up in the app:
  
  UPDATE public.profiles 
  SET role = 'admin' 
  WHERE email = 'mungaimports@gmail.com';
-- 10. SITE VISITS (For Analytics)
CREATE TABLE IF NOT EXISTS site_visits (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  visited_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  path TEXT,
  user_agent TEXT
);

ALTER TABLE site_visits ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public insert to site_visits" ON site_visits FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins can view site_visits" ON site_visits FOR SELECT USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
);

-- 11. EBOOKS
CREATE TABLE IF NOT EXISTS ebooks (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  title TEXT NOT NULL,
  author TEXT,
  description TEXT,
  price_kes NUMERIC DEFAULT 0,
  discount_price_kes NUMERIC,
  cover_image TEXT,
  content TEXT, -- HTML content for online reading
  pdf_url TEXT, -- Link to PDF version
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 12. EBOOK PURCHASES
CREATE TABLE IF NOT EXISTS ebook_purchases (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  book_id UUID REFERENCES ebooks(id) ON DELETE CASCADE,
  purchased_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, book_id)
);

ALTER TABLE ebooks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can view ebooks" ON ebooks FOR SELECT USING (true);
CREATE POLICY "Admin can manage ebooks" ON ebooks FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
);

ALTER TABLE ebook_purchases ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own purchases" ON ebook_purchases FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Allow system insert on purchase" ON ebook_purchases FOR INSERT WITH CHECK (true);
